version: 2.1
jobs:
 
 build:
   docker:
     - image: python:3.7.3-stretch

   working_directory: ~/app

   steps:
     - checkout
     - restore_cache:
         keys:
           - v1-dependencies-{{ checksum "requirements.txt" }}
           - v1-dependencies-

     - run:
        name: install dependencies
        command: |
         python3 -m venv venv
         . venv/bin/activate
         make install
         wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
         chmod +x /bin/hadolint
     - save_cache:
        paths:
         - ./venv
        key: v1-dependencies-{{ checksum "requirements.txt" }}

# run lint!
     - run:
        name: run lint
        command: |
         . venv/bin/activate
           make lint 

 build-image:
   environment:
     IMAGE_NAME: josephjoy038/caprepo
   docker:
     - image: circleci/buildpack-deps:stretch
   working_directory: ~/app
   
   steps:
     - checkout
     - setup_remote_docker
     - run:
         name: Build Docker image
         command: |
           docker build -t $IMAGE_NAME:latest .
     - run:
         name: Archive Docker image
         command: docker save -o image.tar $IMAGE_NAME
     - persist_to_workspace:
         root: ~/app
         paths:
           - .

 publish-image:
   environment:
     IMAGE_NAME: josephjoy038/caprepo
   docker:
     - image: circleci/buildpack-deps:stretch
 
   steps:
      - attach_workspace:
          at: ~/app
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i ~/app/image.tar
      - run:
          name: Publish Docker Image.
          command: |
            docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASS"
            docker push $IMAGE_NAME:latest 

workflows:
  version: 2
  test:
    jobs:
      - build
      - build-image:
         requires: 
           - build
      - publish-image:
         requires: 
           - build-image

